---
# file: roles/consul/meta/main.yml
galaxy_info:
  role_name: consul
  author: Romanov Alex (romanowalex@mail.ru)
  description: Install and configure Consul cluster
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
dependencies:
  - basic
  - firewall